---
title: "WHO"
author: "Sherif Ashraf" 
output: html_document
date: "2024-10-11"
---

Load the Data

```{r WHO}

 #Load the "Life Expectancy Data.csv" dataset 
WHO <- read.csv("Life Expectancy Data.csv")

library(tidyverse)
library(ggplot2)


```
```{r WHO}
# Preview the first 6 rows
head(WHO)

# Display the structure of the WHO dataset
glimpse(WHO)

# print the names of the columns 
names(WHO)


```



modify names of the columns to make easier for us to access them
```{r WHO}
# function to change the names of data fram to lowercase and "." to "_" so we can access it easily
# like for gsub=> https://stackoverflow.com/questions/11776287/remove-pattern-from-string-with-gsub

# function that takes a data frame and modifies its column names
LowerAndDotReplace <- function(data_frame_pass){
      # convert to lowercase
      names(data_frame_pass) <- tolower(names(data_frame_pass))
      # conver . with _ 
      names(data_frame_pass) <- gsub("\\.", "_", names(data_frame_pass))

  return(data_frame_pass)
}


# call the function
WHO <- LowerAndDotReplace(WHO)

# Print the modified column names to verify the changes
names(WHO)


```



```{r WHO}

# Check the class of the 'country' column in the WHO dataset
class(WHO$country)

# Convert the country column to a factor for easier categorical analysis
WHO$country <- as.factor(WHO$country)

# check the conversion by checking the class of the country column again
class(WHO$country)


```



under_five_deaths columns
```{r WHO}

# Check the class of the under_five_deaths
class(WHO$under_five_deaths)

 d#isplay the unique values in the 'under_five_deaths' 
unique(WHO$under_five_deaths)

# Check for na values
WHO %>%
  filter(is.na(under_five_deaths)) %>%
  count()

# display a statistical summary of the under_five_deaths
summary(WHO$under_five_deaths)

# Histogram
hist(WHO$under_five_deaths, main="Histogram of Under-Five Deaths", xlab="Under-Five Deaths")



```




```{r WHO}
class(WHO$polio)
unique(WHO$polio)


summary(WHO$polio)

# check na values
WHO %>%
  filter(is.na(polio)) %>%
  count()

# Remove rows with na values
WHO <- WHO %>%
  filter(!is.na(polio))

# Histogram of Polio
hist(WHO$polio, main="Histogram of Polio", xlab="Polio")





```


Total Expenditure :

```{r WHO}
# Count na values
WHO %>%
  filter(is.na(total_expenditure)) %>%
  count()

# delete rows with NA values
WHO <- WHO %>%
  filter(!is.na(total_expenditure))


summary(WHO$total_expenditure)

# Histogram
hist(WHO$total_expenditure, main="Histogram of Total Expenditure", xlab="Total Expenditure")


```


diphtheria: 

```{r WHO}
# Count missing values
WHO %>%
  filter(is.na(diphtheria)) %>%
  count()


summary(WHO$diphtheria)

# Histogram
hist(WHO$diphtheria, main="Histogram of Diphtheria", xlab="Diphtheria")



```



```{r WHO}
WHO <- read.csv("Life Expectancy Data.csv")

library(tidyverse)

head(WHO)


```




```{r WHO}
# Count na values
WHO %>%
  filter(is.na(hiv_aids)) %>%
  count()


summary(WHO$hiv_aids)

# Histogram
ggplot(WHO, aes(x=hiv_aids)) +
  geom_histogram(color="white") +
  labs(title="Histogram of HIV_AIDS", x="HIV_AIDS", y="Frequency")



```


```{r WHO}
# Count na values
WHO %>%
  filter(is.na(hiv_aids)) %>%
  count()


summary(WHO$hiv_aids)

# Histogram
ggplot(WHO, aes(x=hiv_aids)) +
  geom_histogram(color="white") +
  labs(title="Histogram of HIV_AIDS", x="HIV_AIDS", y="Frequency")



```

```{r WHO}
# Count na values
WHO %>%
  filter(is.na(hiv_aids)) %>%
  count()


summary(WHO$hiv_aids)

# Histogram
ggplot(WHO, aes(x=hiv_aids)) +
  geom_histogram(color="white") +
  labs(title="Histogram of HIV_AIDS", x="HIV_AIDS", y="Frequency")



```





```{r WHO}
# Count na values
WHO %>%
  filter(is.na(gdp)) %>%
  count()

# Remove rows with NA in GDP
WHO <- WHO %>%
  filter(!is.na(gdp))

# Histogram of GDP
ggplot(WHO, aes(x=gdp)) +
  geom_histogram( color="white") +
  labs(title="Histogram of GDP", x="GDP", y="Frequency")


```






```{r WHO}
# Count na values
WHO %>%
  filter(is.na(hiv_aids)) %>%
  count()


summary(WHO$hiv_aids)

# Histogram
ggplot(WHO, aes(x=hiv_aids)) +
  geom_histogram(color="white") +
  labs(title="Histogram of HIV_AIDS", x="HIV_AIDS", y="Frequency")



```




population : 


```{r WHO}
# Count na values
WHO %>%
  filter(is.na(population)) %>%
  count()

# delete rows with NA values
WHO <- WHO %>%
  filter(!is.na(population))


summary(WHO$population)

# Histogram of Population
ggplot(WHO, aes(x=population)) +
  geom_histogram(color="white") +
  labs(title="Histogram of Population", x="Population", y="Frequency")

```

```{r WHO}

#names(WHO)
# Count na values
WHO %>%
  filter(is.na(thinness__1_19_years)) %>%
  count()

# Remove rows with na
WHO <- WHO %>%
  filter(!is.na(thinness__1_19_years))


hist(WHO$thinness__1_19_years, main="Histogram of Thinness (10-19 years)", xlab="Thinness (10-19 years)")

```



```{r WHO}
# Count na values
WHO %>%
  filter(is.na(income_composition_of_resources)) %>%
  count()

# delete rows with na
WHO <- WHO %>%
  filter(!is.na(income_composition_of_resources))

# Histogram of Income Composition of Resources
ggplot(WHO, aes(x=income_composition_of_resources)) +
  geom_histogram( color="white") +
  labs(title="Histogram of Income Composition of Resources", x="Income Composition of Resources", y="Frequency")

```




```{r WHO}
# Count missing values
WHO %>%
  filter(is.na(schooling)) %>%
  count()

# Summary statistics
summary(WHO$schooling)

ggplot(WHO, aes(x=schooling)) +
  geom_histogram(color="white") +
  labs(title="Histogram of Schooling", x="Schooling", y="Frequency")

```



```{r WHO}

names(WHO)
missing_values <- colSums(is.na(WHO))
print(missing_values)

#Handle missing values: remove rows with missing values
#Use this instead of WHO for bigger picture data collection
who_data_clean <- na.omit(WHO)

###Country
#193 countries are being measured
unique(WHO$Country)
class(WHO$Country)
#How many times is each country mentioned
country_counts <- WHO %>%
  count(Country)
print(country_counts)

###Year
#Summary Statistics
summary(WHO$Year)
class(WHO$Year)

###Status
#Summary Statistics
summary(WHO$Status)
class(WHO$Status)

#How many countries are developed versus developing
status_counts <- WHO %>%
  count(Status)
print(status_counts)
#There are 512 developed countries and 2426 developing countries, here is a visualization
ggplot(status_counts, aes(x = Status, y = n, fill = Status)) +
  geom_bar(stat = "identity") +
  labs(title = "Count of Countries by Status",
       x = "Status",
       y = "Count") +
  theme_minimal()

###Life expectancy
#Summary Statistics
summary(WHO$Life.expectancy)
class(WHO$Life.expectancy)
#Visualization
WHO %>%
  filter(is.na(Life.expectancy)) %>%
  count()
summary(WHO$Life.expectancy)
hist(WHO$Life.expectancy, main="Histogram of Life Expectancy", xlab="Life Expectancy")

#Calculate mean life expectancy for each year
mean_life_expectancy <- WHO %>%
  group_by(Year) %>%
  summarize(Mean_Life_Expectancy = mean(Life.expectancy, na.rm = TRUE))
print(mean_life_expectancy)
#Life expectancy has been slowly rising from 2000-2015
#Histogram
ggplot(mean_life_expectancy, aes(x = Year, y = Mean_Life_Expectancy)) +
  geom_bar(stat = "identity", fill = "blue", color = "black") +
  labs(title = "Mean Life Expectancy by Year",
       x = "Year",
       y = "Mean Life Expectancy")

###Adult mortality
#Summary Statistics
summary(WHO$adult.mortality)
class(WHO$Adult.Mortality)
hist(WHO$Adult.Mortality, main="Histogram of Adult Mortality", xlab="Adult Mortality Rate")

###Infant deaths
#Summary Statistics
summary(WHO$infant.deaths)
class(WHO$infant.deaths)
hist(WHO$infant.deaths, main="Histogram of Infant Deaths", xlab="Infant Deaths")


###Alcohol
#Summary Statistics
summary(WHO$Alcohol)
class(WHO$Alcohol)
hist(WHO$Alcohol, main="Histogram of Alcohol Consumption", xlab="Alcohol Consumption (in litres)")


###Percentage Expenditure
#Summary Statistics
summary(WHO$percentage.expenditure)
class(WHO$percentage.expenditure)
hist(WHO$percentage.expenditure, main="Histogram of Percentage Expenditure", xlab="Percentage Expenditure (% of GDP per capita)")


###Hepatitis B
#Summary Statistics
summary(WHO$Hepatitis.B)
class(WHO$Hepatitis.B)
hist(WHO$Hepatitis.B, main="Histogram of Hepatitis B", xlab="Hepatitis B immunization coverage among 1-year-olds (%)")



###Measles
#Summary Statistics
summary(WHO$Measles)
class(WHO$Measles)
hist(WHO$Measles, main="Histogram of Measles", xlab="Measles - number of reported cases per 1000 population")


###BMI
#Summary Statistics
summary(WHO$BMI)
class(WHO$BMI)
hist(WHO$BMI, main="Histogram of BMI", xlab="Average Body Mass Index of entire population")

```










